apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/jacekzubielik/node-app
  # newName: docker.io/kostiscodefresh/simple-web-app
  newTag: 2.1.13


