---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-prom-volume
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 9Gi
  storageClassName: local-path #local-storage #local-path

