apiVersion: v1
kind: Service
metadata:
  name: node-app
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: node-app
spec:
  ports:
    - protocol: TCP
      port: 8000
      name: http
      targetPort: 3000
  selector:
    app: node-app
    task: node-app
