apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: prod
resources:
- ../../base
- resources/deployment.yaml
- resources/service.yaml

metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true, ServerSideApply=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "10"
  labels:
    app.kubernetes.io/name: demo-app
  name: demo-app

configMapGenerator:
- name: demo-app-config
  literals:
  - TZ=CET

