---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true, ServerSideApply=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: '{{ sync-Wave }}'
  labels:
    app.kubernetes.io/name: node-app

configMapGenerator:
- name: node-app-config
  literals:
  - TZ=CET