apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- ../../base

metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true, ServerSideApply=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/hook: PreSync
  # labels:
  #   app.kubernetes.io/name: binance-proxy
  labels:
    appId: binance-proxy

helmCharts:
  - name: binance-proxy
    version: 0.0.4
    repo: https://jacekzubielik.github.io/jz-helm-charts
    releaseName: binance-proxy
    includeCRDs: false
    valuesFile: values.yaml

# Here's the warning fix
patches:
  - target:
      kind: CustomResourceDefinition
    patch: |- 
      - op: remove
        path: /metadata/labels/app.kubernetes.io~1instance