apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- resources/deployment.yaml
# - resources/ingressroute.yaml
- resources/service.yaml
# - resources/namespace.yaml

configMapGenerator:
- name: whoami-frontend-config
  literals:
  - TZ=CET



