apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    app.kubernetes.io/name: sealed-secrets

helmCharts:
- name: sealed-secrets
  repo: https://bitnami-labs.github.io/sealed-secrets
  version: 2.14.2
  releaseName: sealed-secrets
  namespace: kube-system
  includeCRDs: false
  valuesFile: values.yaml

configMapGenerator:
- name: sealed-secrets-config
  literals:
  - TZ=CET

# Workaround for:
#
#   https://github.com/bitnami-labs/sealed-secrets/issues/894
#
#   when trying to create a sealed secret from yaml or json output via kubeseal
#
#     error: unable to recognize "sealedsecret.json": no matches for kind "SealedSecret" in version "bitnami.com/v1alpha1"
#   in sealed-secrets controller logs:
#
#     W0728 21:19:14.949824       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.4/tools/cache/reflector.go:167: failed to list *v1alpha1.SealedSecret: the server could not find the requested resource (get sealedsecrets.bitnami.com)
#     E0728 21:19:14.949888       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.4/tools/cache/reflector.go:167: Failed to watch *v1alpha1.SealedSecret: failed to list *v1alpha1.SealedSecret: the server could not find the requested resource (get sealedsecrets.bitnami.com)
#
# XXX: superceded via 'includeCRDs: true' in helmCharts section above
# resources:
# - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.24.4/controller.yaml
