apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: ingress-nginx
resources:
- ../../base
- resources/priorityclass.yaml

metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true, ServerSideApply=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: ingress-nginx
  name: ingress-nginx

helmCharts:
  - name: ingress-nginx
    version: 4.10.1
    repo: https://kubernetes.github.io/ingress-nginx
    releaseName: ingress-nginx
    includeCRDs: true
    valuesFile: values2.yaml

configMapGenerator:
- name: ingress-nginx-config
  literals:
  - TZ=CET

patches:
#   - path: internal-loadbalancer-service.patch.yaml
  # enable this for dev / staging environments to use internal IP load balancer only
  # - patches/internal-loadbalancer-service.patch.yaml

  - path: pdb.patch.yaml
    target:
      group: policy
      version: v1
      kind: PodDisruptionBudget
      name: ingress-nginx-controller
      namespace: ingress-nginx