apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: ingress-nginx
resources:
- ../../base

metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true, ServerSideApply=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: ingress-nginx

helmCharts:
  - name: ingress-nginx
    version: 4.10.0
    repo: https://kubernetes.github.io/ingress-nginx
    releaseName: ingress-nginx
    includeCRDs: false
    # valuesFile: values.yaml

