apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- ../../base

helmCharts:
  - name: binance-proxy
    version: 0.0.4
    repo: https://jacekzubielik.github.io/jz-helm-charts
    releaseName: binance-proxy
    includeCRDs: false
    valuesFile: values.yaml