apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trade
resources:
- ../../base

metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  # labels:
  #   app.kubernetes.io/name: binance-proxy

helmCharts:
  - name: binance-proxy
    version: 0.0.4
    repo: https://jacekzubielik.github.io/jz-helm-charts
    releaseName: binance-proxy
    includeCRDs: false
    valuesFile: values.yaml