replicaCount: 2

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
timezone: CET

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP #ClusterIP LoadBalancer
  externalIPs: []
  loadBalancerIP: [] #"192.168.40.185"
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
      name: port-spot
    - port: 8091
      targetPort: 8091
      protocol: TCP
      name: port-futures

resources:
  limits:
    memory: 0.3Gi
    cpu: 350m
  requests:
    memory: 0.2Gi
    cpu: 150m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  averageCPUUtilizationPercentage: 50
  averageMemoryUtilizationPercentage: 50

  nodeSelector:
    kubernetes.io/hostname: k8s-argocd-autopilot-playground-control-plane

tolerations: []

affinity: {}
