apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true, ServerSideApply=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: metallb
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    existingConfigMap: metallb-config
  name: dev-lb-iprange
spec:
  addresses:
  - 192.168.40.180-192.168.40.200
  autoAssign: true
  avoidBuggyIPs: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  # namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: metallb
  name: l2-advertisement 
spec:
  ipAddressPools:
  - dev-lb-iprange
  nodeSelector: {}
    # kubernetes.io/hostname: k8s-playground-control-plane



