apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
#   annotations:
#     argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
#     argocd.argoproj.io/sync-wave: '{{ sync-Wave }}'
  labels:
    app.kubernetes.io/name: node-app
  #   app: node-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: node-app
  template:
    spec:
      containers:
        - name: node-app
          image: ghcr.io/jacekzubielik/node-app:2.1.13
          ports:
          - containerPort: 3000
          envFrom:
          - configMapRef:
              name: node-app-config
          resources:
            requests:
              memory: "16Mi" 
              cpu: "50m"    # 500milliCPUs (1/2 CPU)
            limits:
              memory: "128Mi"
              cpu: "100m"
