apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
#   annotations:
#     argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
#     argocd.argoproj.io/sync-wave: '{{ sync-Wave }}'
#   labels:
#     app.kubernetes.io/name: node-app

spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: node-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-app
    spec:
      containers:
        - image: ghcr.io/jacekzubielik/node-app:2.1.13
          name: node-app
          ports:
          - containerPort: 3000
