apiVersion: v1
kind: Service
metadata:
  name: node-app
#   annotations:
#     argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
#     argocd.argoproj.io/sync-wave: '{{ sync-Wave }}'
  labels:
    app: node-app
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: node-app
