creation_rules:
  - unencrypted_regex: '^(apiVersion|metadata|kind|type)$'
    pgp: '6D3FE55384B558E06A1BA364586EFA784A32C981'
    age: 'age1deg9tqt7jtddnqme6nvcl72czns80z0n25u8k9pw5830dn4arsks5pua4h'
