apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: kustomize-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
secretFrom:
- metadata:
    name: private-domain
  type: Opaque
  files:
  - private-domain=secrets/secret.enc.yaml
