apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: kustomize-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
secretFrom:
- metadata:
    name: private-domain
    annotations:
      kustomize.config.k8s.io/needs-hash: "false"
  type: Opaque
  files:
  - ./secrets/secret.enc.yaml
