apiVersion: v1
kind: Secret
metadata:
    # annotations:
    #   # replace the base secret data/stringData values with these encrypted data/stringData values
    #   kustomize.config.k8s.io/behavior: replace
    name: login
    namespace: dev
type: Opaque
data:
    username: ENC[AES256_GCM,data:1PZgmmuZqpw=,iv:JsOypVzL/kSgwquoJSnQ8Eb0sa0QIAOPuw+YtDKbjss=,tag:E3A7ODFYrIiqlaCzdSZW4Q==,type:str]
    password: ENC[AES256_GCM,data:tn884VpKUMIMl9HbX0seAw==,iv:QfvWRGVIiub1pGZX2D85XtUWi78LIEvKkqz0zHQ2HiM=,tag:kP80VtBDaprnRQVyJyPH2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1deg9tqt7jtddnqme6nvcl72czns80z0n25u8k9pw5830dn4arsks5pua4h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbEFWSzZ3UThLSnp2N1d1
            NzcwSDRsdEpEUkFlRnFQOVBvUUpGa3dFZVM0Cmdycm1NMmZPODRRK1VaVUhoRzZh
            OTYvZFo0M3pxTmlkVDVYdUp0cURLa1UKLS0tIG1TVUY5RmVURlBtbCtpbG5GU1dT
            c1hwendqQnNUM3c4bFNRL0VlSXZ6eTAKPxMwd1449U+4XPkNRb8K4q4Kbiu2SPkP
            KobO0cM4Vk2kpEkxlnnk6f988+Qan0Pomd7+8C3/j96Oc2rnpVVyDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-13T08:23:29Z"
    mac: ENC[AES256_GCM,data:mgMNzTQOW4UUtpfnIBN/X0rKPJDaS32pJT7zGLX+S7Hf4hfx5wKSM3cGVdfsjcfo31hkHPhZrSYK9JUOL6/mL2WmXPrf6mPQt5q9XXxLatKg1rDXYXB8biJnRqFNwkZKM6S2U9VxNhICUVRkvM4PoF2Q01rvHrPNsSCBc+m5wFQ=,iv:ftl5gOkz0tkSMMoX8J3tcVjJMGxpHHNPV755fEjBrqE=,tag:2+LwrF5ZFEHdkQRWSBvv1g==,type:str]
    pgp:
        - created_at: "2024-06-13T08:23:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0R6oz1GmNjVARAAskicqEXhdfiPiva9sqFnqFhf2PlyyQ6/EGECDo08hmh7
            eY5/O/bTGZ3AyHz/12ZCIZvjeebja/yv0dZJePupvzkVRh69Fkq62HILeF8mDZmV
            k9E/NCpiQagiBGJRAfec9TMK3rsHeY9ad1d3HcHMZ++jciDzo307hNVcSbpoZeVJ
            U+kXftjvpCgkULLzIkfI4j1HkhdpFhYqzgVaQisu1tDgFnEz+8xUmzGSfbOPgHe5
            gu0V4ugbUGJAPDtLxQtLyP4NFF4iZZelp34mzvuvexgJ4VyX9A6Vw7N0VgEKxIRM
            jUe+9X5WpYz+E2l/rQX5XVKGdxz2yRtswT1meRL7lBUkjKZtYsIr+CVnriCQs85B
            wrV/2c07XLRMNm8sIHLlTmQpe37FtuLdSO5iaTTUCyPahL/kBkIbKLNf1XsgPbYl
            BwNNZYtWk2wQl/GXkkNmheoyKaPqbPf/TKJ8CSRz7TR2to4OrVV7wC/qIqh0d/c5
            0IXcRS0zSWSmRURPXUg3DebMOrO0c3CQRuq1WuknCJSq/FaBFgHiHY6QwDm3HPAk
            DowjOgDp/ozz2jhm1I5PvDB+ReehJDBpO2hLyEzkS8LKMWFlJHRru/2Q6m69991U
            M9V9NUgKCivbnWYB0hP0QLTdLDa6q+efh7u1pHqLwbxyX7KrCLZliVD4YokV8n7S
            XgHLKciPkq1mIg1mbqnl1ExIXy1/pReU03FazaUe/9uQVoaS3HO9v9xV5ibIFuQa
            rJUJ6RWBknaWQ5t6oXG1wEVPQIMlBkjCShpW2Ycc11lZ+BwNilV6S/sn1+9Q9b4=
            =SZPh
            -----END PGP MESSAGE-----
          fp: 6D3FE55384B558E06A1BA364586EFA784A32C981
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.1
