apiVersion: v1
kind: Secret
metadata:
    # annotations:
    #     # replace the base secret data/stringData values with these encrypted data/stringData values
    #     kustomize.config.k8s.io/behavior: replace
    name: login
    namespace: dev
type: Opaque
data:
    username: ENC[AES256_GCM,data:/blXcfhhMH8=,iv:Y8A4wYKnEgbWDyPJ+KeJjt2a+c/gzncqxH4xp5KN1N0=,tag:D3MYpKU7OIrlf7pdIMONnA==,type:str]
    password: ENC[AES256_GCM,data:mOMcjGXlDapcVyErOpC7Mg==,iv:P2XKLuq0khYzLRTAUWEy8+VFyWQps5uEgsSX62odqdk=,tag:wyG584+Nb2GXyQK187n7yg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1deg9tqt7jtddnqme6nvcl72czns80z0n25u8k9pw5830dn4arsks5pua4h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadlZGZ0FQOWxHSDhsVVdB
            NkRNZEpudU1mRWlWYm9MQXdoSWNwRENHN1JVCmNnbFEwQWEyR3JBSmZ3VlVUYnZ1
            NG9INEhMbmFPRzFIWVk4a3N6NXg0Mk0KLS0tIGhHeE9nV0E0czd2TDJ1bGVEWG01
            Q1NKZHhqUzFmZ1NDQ2Job3ZTQ3FoOFEKNbGOxvbclZQMCTo8bAxEeJr8F18vqLS/
            A87XaGc9t27k5uyElmzYXU0J/MQW4xRcVht9bDmccK2ta0EyJHLPGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-13T08:10:44Z"
    mac: ENC[AES256_GCM,data:vm99dvW24v5/mP0AIBeIdZ2OdE2CJog3w1bDAwg0uSIEYTKGSzE8cn5hO4HZXUw+SczjZhjeEbCwc1nloui3O1UDxHhRKLijpmZ/f8B7sjh0HJIA2v3PZixWEaGJ2+zumc7PpF0g1yQGbluwOi1WS1W3/N6WGriIH5NLS+BgmsM=,iv:VnlPTxk92OzApnOzkgM0ei1DTP5qkufwAd9Pq1l3598=,tag:tksXUF2QF0xWzbPl5y27bQ==,type:str]
    pgp:
        - created_at: "2024-06-13T08:10:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0R6oz1GmNjVAQ//WRhmozbQRoY4zFdBAun2i10W9V3D67NE8SHWRDSEKE9B
            7YvyPrrY7n6dY4SzlEFF0UEqGYSmRE977q68Q3FyQXmxqZdAPzwY+ZW04c/97w9L
            LfXfNZ4Kn1Tw3NZRjeK6pdCzgeQ1HQ1PqqI9knvQBOylMncMTsSm5KDhzc2+7yu3
            7xYvPAALCVo5mqvbWwwwmVXrq3tH9ST8KZuWghGTLLsJIuzWvZ7B9d4WVUcEj+ld
            LkW6lzm9Da/SFnvoq+M2TouS/MWXJmspgxTpb5aQh6eNJ9zZm8a7zPHDngM2BTM4
            dp0l6wYt/dcFfe7foScxkU0TUyYuNCmtuGJgYknUTdz6+5R6YwsEZJGjGwqV0nqq
            rKxycfPK509QKVl0Lbu6U3JMbXuAcu0hsn/TfGX5cx2O7R9Cc8t9dn26tAzup2f0
            AZV8AfWgIp0DizTfBf/CbRBh1o5wNfVKXXOXGe0WLe3T3EXkHvG4Zetm2ZyY89ZJ
            U74j+IVhsyU9Z8kBIA6vEaHTWCiWk0IbGz08X1p2BQ67BogUDBlcaqKn6+60fMBc
            s34TY35opCvL3UFl2xtroKtzaskZ7ZSR18x8nHJoX20wLD2ndM62MXocjhfUnbbd
            s49L6bHfULaRX7dXhncEc5P1ERJwE3vdZtMCOySLlIO6pBhfBTgqhchAEU5OIgHS
            XAGRWRnXZRR3AT1nVZAq2Fg35wtyX2kBGrjVxWyfL62WS8KInkk6Hkdo2Am6RftF
            PnAzhOakiD4X16eR6ADAtQsuZw7dvLaaOMaCR1oCqFvhJDu+AP05AGbypdEk
            =XoFy
            -----END PGP MESSAGE-----
          fp: 6D3FE55384B558E06A1BA364586EFA784A32C981
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.1
