---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true, ServerSideApply=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: metallb
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    existingConfigMap: metallb-config
  name: metallb

helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: 0.14.3
    releaseName: metallb
    includeCRDs: true
    valuesFile: values.yaml
    valuesInline:
      spec:
        ignoreDifferences:
          # ------------- MetalLB patch
          - group: "apiextensions.k8s.io"
            kind: CustomResourceDefinition
            name: bgppeers.metallb.io
            jsonPointers:
              - /spec/conversion/webhook/clientConfig/caBundle
          - group: "apiextensions.k8s.io"
            kind: CustomResourceDefinition
            name: addresspools.metallb.io
            jsonPointers:
              - /spec/conversion/webhook/clientConfig/caBundle

configMapGenerator:
  - name: metallb-config
    literals:
      - TZ=CET

patchesJson6902:
  - path: patches/metallb-no-deprecation-warning.yaml
    target:
      group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: addresspools.metallb.io
      version: v1
