---
apiVersion: v1
kind: PersistentVolume
metadata:
  # annotations:
  #   argocd.argoproj.io/sync-wave: "4"
  labels:
    #app.kubernetes.io/name: hello-world-frontend
    type: local
  name: hello-world-pv-volume

spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi

  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: "/mnt/volume-0/PV/hello-world-pv-volume"




