apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-frontend
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app.kubernetes.io/name: hello-world-frontend

spec:
  selector:
    matchLabels:
      app: excalidraw
  template:
    metadata:
      labels:
        app: excalidraw
    containers:
    - name: excalidraw
      image: kostiscodefresh/simple-web-app:latest


