---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# override namespace for all resources
# may cause duplicate namespace clashes if different namespaces are defined in bases
#namespace: cattle-system # XXX: Do not set this if using remote base or Helm charts - may override creating roles for kube-system for leader election etc. eg. for Cert Manager

resources:
  - namespace.yaml
  #- ../../cert-manager/base

helmCharts:
  - name: rancher
    repo: https://releases.rancher.com/server-charts/latest
    version: 2.8.4
    releaseName: rancher
    namespace: cattle-system
    includeCRDs: true
    valuesFile: values.yaml
