# ArgoCD config file
appName: node-app
userGivenName: node-app
destNamespace: dev
destServer: https://kubernetes.default.svc
srcPath: apps/node-app/overlays/dev-test
srcRepoURL: https://github.com/jacekzubielik/k8s-argocd-autopilot-playground.git
srcTargetRevision: HEAD
syncWave: 10
appRole: dev
labels: ""
annotations: ""
exclude: ""
include: ""
