apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: node-app
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "10"
  labels:
    app.kubernetes.io/name: node-app
resources:
- ../../base
- resources/deployment.yaml
- resources/service.yaml
- resources/ingress.yaml