apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-frontend
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: whoami-frontend
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: whoami-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: whoami-frontend
    spec:
      containers:
        - name: whoami-frontendpp
          image: ghcr.io/traefik/whoami:v1.10.2
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
          envFrom:
          - configMapRef:
              name: whoami-frontend-config
          resources:
            requests:
              memory: "256Mi" 
              cpu: "250m"    # 500milliCPUs (1/2 CPU)
            limits:
              memory: "512Mi"
              cpu: "500m"
